"use client";

import { useEffect, useState } from "react";

type Account={id:number;person:string;name:string;status:string;balance:number};
type Statement={account:Account;period:{from:string;to:string};opening:{balance:number;principal:number;interest:number;fees:number};closing:{balance:number;principal:number;interest:number;fees:number};interest_accrued:number;interest_paid:number;debits:number;credits:number;transactions:Array<{transaction_id:number;date:string;type:string;direction:string;amount:number;interest_accrual_before_transaction:number;allocated_to_fees:number;allocated_to_interest:number;allocated_to_principal:number;balance_after:number;note:string}>};
type Annual={year:number;accounts:Array<{account_id:number;person:string;account:string;status:string;opening_balance:number;closing_balance:number;interest_accrued:number;interest_paid:number;principal_at_year_end:number}>;totals:{opening_balance:number;closing_balance:number;interest_accrued:number;interest_paid:number;principal_at_year_end:number}};
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000/api";const money=new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"});const iso=(d:Date)=>d.toISOString().slice(0,10);
async function api<T>(path:string):Promise<T>{const r=await fetch(`${API}${path}`);if(!r.ok){const b=await r.json().catch(()=>({detail:"Request failed"}));throw new Error(b.detail||"Request failed")}return r.json() as Promise<T>}
export default function ReportsPage(){
  const now=new Date();const [accounts,setAccounts]=useState<Account[]>([]);const [accountId,setAccountId]=useState("");const [fromDate,setFromDate]=useState(`${now.getFullYear()}-01-01`);const [toDate,setToDate]=useState(iso(now));const [year,setYear]=useState(String(now.getFullYear()));const [statement,setStatement]=useState<Statement|null>(null);const [annual,setAnnual]=useState<Annual|null>(null);const [error,setError]=useState("");
  async function loadAccounts(){try{const a=await api<{accounts:Account[]}>("/managed-accounts?include_archived=true");setAccounts(a.accounts);const id=accountId||String(a.accounts[0]?.id||"");if(!accountId&&id)setAccountId(id);if(id)await loadStatement(id);await loadAnnual(year);setError("")}catch(e){setError(e instanceof Error?e.message:"Backend unavailable")}}
  async function loadStatement(id=accountId){if(!id)return;try{setStatement(await api<Statement>(`/reports/accounts/${id}/statement?from_date=${fromDate}&to_date=${toDate}`));setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load statement")}}
  async function loadAnnual(y=year){try{setAnnual(await api<Annual>(`/reports/annual-interest/${y}`));setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load annual report")}}
  useEffect(()=>{void loadAccounts()},[]);
  const statementCsv=accountId?`${API}/reports/accounts/${accountId}/statement.csv?from_date=${fromDate}&to_date=${toDate}`:"#";const annualCsv=`${API}/reports/annual-interest/${year}.csv`;
  return <div className="phase7-page"><header className="topbar"><div className="brand"><span className="brand-mark">BM</span><span>Bank of Mum</span></div><div className="workspace-title">Family accounting workspace <span>Phase 7 · reports & statements</span></div><div className="connection online"><i/>Deterministic reports</div></header><main className="phase7-workspace">
    <section className="page-head"><div><p className="eyebrow">BANK OF MUM</p><h1>Reports</h1><p>Statements and annual interest summaries calculated from the immutable dated ledger.</p></div><div className="phase7-actions"><a className="quiet-button" href="/maintenance">Maintenance</a><a className="primary" href="/">Back to dashboard</a></div></section>{error&&<div className="notice error">{error}</div>}
    <section className="panel"><div className="panel-head"><div><p className="eyebrow">ACCOUNT STATEMENT</p><h2>Statement period</h2></div></div><div className="report-controls"><label>Account<select value={accountId} onChange={e=>setAccountId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.person} · {a.name}</option>)}</select></label><label>From<input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/></label><label>To<input type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/></label><button className="primary" onClick={()=>void loadStatement()}>Run statement</button><a className="download-link" href={statementCsv}>Download CSV</a></div>
      {statement&&<><div className="phase7-cards" style={{padding:"16px 18px 0"}}><article><small>Opening balance</small><strong>{money.format(statement.opening.balance)}</strong><span>{statement.period.from}</span></article><article><small>Interest accrued</small><strong>{money.format(statement.interest_accrued)}</strong><span>{money.format(statement.interest_paid)} paid</span></article><article><small>Credits</small><strong>{money.format(statement.credits)}</strong><span>{money.format(statement.debits)} debits</span></article><article><small>Closing balance</small><strong>{money.format(statement.closing.balance)}</strong><span>Principal {money.format(statement.closing.principal)}</span></article></div><div className="table-scroll"><table className="phase7-table"><thead><tr><th>Date</th><th>Type</th><th>Direction</th><th>Amount</th><th>Interest before</th><th>To fees</th><th>To interest</th><th>To principal</th><th>Balance</th><th>Note</th></tr></thead><tbody>{statement.transactions.map(row=><tr key={row.transaction_id}><td>{row.date}</td><td>{row.type}</td><td>{row.direction}</td><td className="money">{money.format(row.amount)}</td><td className="money">{money.format(row.interest_accrual_before_transaction)}</td><td className="money">{money.format(row.allocated_to_fees)}</td><td className="money">{money.format(row.allocated_to_interest)}</td><td className="money">{money.format(row.allocated_to_principal)}</td><td className="money"><strong>{money.format(row.balance_after)}</strong></td><td>{row.note||"—"}</td></tr>)}</tbody></table></div></>}
    </section><div style={{height:16}}/>
    <section className="panel"><div className="panel-head"><div><p className="eyebrow">ANNUAL INTEREST</p><h2>Year summary</h2></div></div><div className="report-controls"><label>Year<input type="number" min="2000" max="2200" value={year} onChange={e=>setYear(e.target.value)}/></label><button className="primary" onClick={()=>void loadAnnual()}>Run annual report</button><a className="download-link" href={annualCsv}>Download CSV</a></div>{annual&&<><div className="phase7-cards" style={{padding:"16px 18px 0"}}><article><small>Opening balance</small><strong>{money.format(annual.totals.opening_balance)}</strong><span>{annual.year}</span></article><article><small>Interest accrued</small><strong>{money.format(annual.totals.interest_accrued)}</strong><span>Across all accounts</span></article><article><small>Interest paid</small><strong>{money.format(annual.totals.interest_paid)}</strong><span>Allocated payments</span></article><article><small>Closing balance</small><strong>{money.format(annual.totals.closing_balance)}</strong><span>Principal {money.format(annual.totals.principal_at_year_end)}</span></article></div><div className="table-scroll"><table className="phase7-table"><thead><tr><th>Person / account</th><th>Status</th><th>Opening</th><th>Interest accrued</th><th>Interest paid</th><th>Closing</th><th>Year-end principal</th></tr></thead><tbody>{annual.accounts.map(row=><tr key={row.account_id}><td><strong>{row.person} · {row.account}</strong></td><td><span className={`status-pill ${row.status}`}>{row.status}</span></td><td className="money">{money.format(row.opening_balance)}</td><td className="money">{money.format(row.interest_accrued)}</td><td className="money">{money.format(row.interest_paid)}</td><td className="money"><strong>{money.format(row.closing_balance)}</strong></td><td className="money">{money.format(row.principal_at_year_end)}</td></tr>)}</tbody></table></div></>}
    </section>
  </main></div>
}
