"use client";

import { useEffect, useState } from "react";

type Backup={filename:string;valid:boolean;created_at?:string;sha256?:string;integrity?:string;size:number;error?:string};
type Verification={phase:number;database_integrity:string;ledger_integrity:Array<{ok:boolean;account_id?:number}>;counts:{people:number;accounts:number;transactions:number;interest_rate_periods:number;audit_events:number};warnings:string[];ok:boolean};
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000/api";const bytes=(n:number)=>n>1024*1024?`${(n/1024/1024).toFixed(2)} MB`:`${Math.max(1,Math.round(n/1024))} KB`;
async function api<T>(path:string,options?:RequestInit):Promise<T>{const r=await fetch(`${API}${path}`,options);if(!r.ok){const b=await r.json().catch(()=>({detail:"Request failed"}));throw new Error(b.detail||"Request failed")}return r.json() as Promise<T>}
export default function MaintenancePage(){
  const [backups,setBackups]=useState<Backup[]>([]);const [verification,setVerification]=useState<Verification|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  async function refresh(){try{const [b,v]=await Promise.all([api<{backups:Backup[]}>("/maintenance/backups"),api<Verification>("/maintenance/verification")]);setBackups(b.backups);setVerification(v);setError("")}catch(e){setError(e instanceof Error?e.message:"Backend unavailable")}}
  useEffect(()=>{void refresh()},[]);
  async function createBackup(){setBusy(true);try{const result=await api<{backup:Backup}>("/maintenance/backups",{method:"POST"});setNotice(`Backup ${result.backup.filename} created and validated`);await refresh()}catch(e){setError(e instanceof Error?e.message:"Could not create backup")}finally{setBusy(false)}}
  async function restore(item:Backup){if(!item.valid)return;const confirmation=window.prompt(`Restore ${item.filename}? This replaces the live database. Type RESTORE exactly.`);if(confirmation!=="RESTORE")return;setBusy(true);try{const result=await api<{pre_restore_backup:string}>(`/maintenance/backups/${encodeURIComponent(item.filename)}/restore`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmation})});setNotice(`Restore complete. Automatic safety backup: ${result.pre_restore_backup}`);await refresh()}catch(e){setError(e instanceof Error?e.message:"Restore failed")}finally{setBusy(false)}}
  return <div className="phase7-page"><header className="topbar"><div className="brand"><span className="brand-mark">BM</span><span>Bank of Mum</span></div><div className="workspace-title">Family accounting workspace <span>Phase 7 · maintenance & recovery</span></div><div className={`connection ${verification?.ok?"online":""}`}><i/>{verification?.ok?"Integrity OK":"Check status"}</div></header><main className="phase7-workspace">
    <section className="page-head"><div><p className="eyebrow">BANK OF MUM</p><h1>Maintenance</h1><p>Validated backups, confirmed restore and end-to-end accounting integrity checks.</p></div><div className="phase7-actions"><a className="quiet-button" href="/reports">Reports</a><a className="primary" href="/">Back to dashboard</a></div></section>{error&&<div className="notice error">{error}</div>}{notice&&<div className="notice success">{notice}</div>}
    <div className="phase7-warning">Restore is intentionally guarded. Every restore requires the exact confirmation word <strong>RESTORE</strong>, validates the archive checksum and SQLite integrity first, and creates a fresh pre-restore backup automatically.</div><div style={{height:16}}/>
    <section className="phase7-grid equal"><div className="panel maintenance-card"><h3>Integrity verification</h3><p>Checks SQLite integrity, every account ledger hash chain, opening-balance presence, rate history and orphan planning/scenario links.</p>{verification?<div className="verification-list"><div><span>Overall</span><strong className={verification.ok?"ok-text":"warn-text"}>{verification.ok?"PASS":"REVIEW"}</strong></div><div><span>SQLite</span><strong>{verification.database_integrity}</strong></div><div><span>People / accounts</span><strong>{verification.counts.people} / {verification.counts.accounts}</strong></div><div><span>Transactions</span><strong>{verification.counts.transactions}</strong></div><div><span>Rate periods</span><strong>{verification.counts.interest_rate_periods}</strong></div><div><span>Audit events</span><strong>{verification.counts.audit_events}</strong></div><div><span>Ledger chains checked</span><strong>{verification.ledger_integrity.length}</strong></div>{verification.warnings.map((w,i)=><div key={i}><span>Warning</span><strong className="warn-text">{w}</strong></div>)}</div>:<p>Loading verification…</p>}<div style={{height:12}}/><button className="quiet-button" onClick={()=>void refresh()}>Run verification again</button></div>
      <div className="panel maintenance-card"><h3>Backup policy</h3><p>Backups are SQLite snapshots written with the SQLite backup API, wrapped in ZIP with a manifest and SHA-256 checksum.</p><div className="verification-list"><div><span>Storage</span><strong>data-v2/backups</strong></div><div><span>Format</span><strong>ZIP + manifest</strong></div><div><span>Checksum</span><strong>SHA-256</strong></div><div><span>Restore safety</span><strong>Pre-restore snapshot</strong></div></div><div style={{height:14}}/><button className="primary" disabled={busy} onClick={()=>void createBackup()}>{busy?"Working…":"Create validated backup"}</button></div></section>
    <div style={{height:16}}/><section className="panel"><div className="panel-head"><div><p className="eyebrow">RECOVERY POINTS</p><h2>Available backups</h2></div><span>{backups.length}</span></div>{backups.length?backups.map(item=><div className="backup-row" key={item.filename}><div><strong>{item.filename}</strong><small>{item.created_at?new Date(item.created_at).toLocaleString("en-GB"):item.error||"Unknown date"}</small></div><div><span className={`status-pill ${item.valid?"":"paused"}`}>{item.valid?"valid":"invalid"}</span><small>{item.integrity||item.error||""}</small></div><div><strong>{bytes(item.size)}</strong><small>{item.sha256?.slice(0,12)||"no checksum"}</small></div><div className="phase7-actions"><a className="download-link" href={`${API}/maintenance/backups/${encodeURIComponent(item.filename)}`}>Download</a><button className="danger-button" disabled={!item.valid||busy} onClick={()=>void restore(item)}>Restore</button></div></div>):<div className="empty">No backups created yet.</div>}</section>
  </main></div>
}
