"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Person={id:number;name:string;notes:string;accounts:number;active_accounts:number};
type Account={id:number;person_id:number;person:string;name:string;account_type:string;opening_principal:number;annual_interest_rate:number;regular_payment:number;start_date:string|null;status:string;principal:number;accrued_interest:number;fees:number;balance:number};
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000/api";
const money=new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"});
const today=()=>new Date().toISOString().slice(0,10);
async function api<T>(path:string,options?:RequestInit):Promise<T>{const r=await fetch(`${API}${path}`,options);if(!r.ok){const b=await r.json().catch(()=>({detail:"Request failed"}));throw new Error(b.detail||"Request failed")}return r.json() as Promise<T>}

export default function ManagePage(){
  const [people,setPeople]=useState<Person[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const [personName,setPersonName]=useState("");const [personNotes,setPersonNotes]=useState("");
  const [personId,setPersonId]=useState("");const [accountName,setAccountName]=useState("");const [principal,setPrincipal]=useState("");const [rate,setRate]=useState("0");const [payment,setPayment]=useState("");const [startDate,setStartDate]=useState(today());const [convention,setConvention]=useState("actual_365");
  const activeAccounts=useMemo(()=>accounts.filter(item=>item.status!=="archived"),[accounts]);
  async function refresh(){try{const [p,a]=await Promise.all([api<{people:Person[]}>("/people"),api<{accounts:Account[]}>("/managed-accounts?include_archived=true")]);setPeople(p.people);setAccounts(a.accounts);if(!personId&&p.people[0])setPersonId(String(p.people[0].id));setError("")}catch(e){setError(e instanceof Error?e.message:"Backend unavailable")}}
  useEffect(()=>{void refresh()},[]);
  async function addPerson(event:FormEvent){event.preventDefault();if(!personName.trim())return;try{await api("/people",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:personName,notes:personNotes})});setPersonName("");setPersonNotes("");setNotice("Person created");await refresh()}catch(e){setError(e instanceof Error?e.message:"Could not create person")}}
  async function editPerson(item:Person){const name=window.prompt("Name",item.name)?.trim();if(!name)return;const notes=window.prompt("Notes",item.notes)??item.notes;const reason=window.prompt("Reason for change","Person details updated")?.trim();if(!reason)return;try{await api(`/people/${item.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,notes,reason})});setNotice("Person updated and audited");await refresh()}catch(e){setError(e instanceof Error?e.message:"Could not update person")}}
  async function addAccount(event:FormEvent){event.preventDefault();if(!personId||!accountName.trim())return;try{await api("/managed-accounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({person_id:Number(personId),name:accountName,account_type:"loan",opening_principal:principal||"0",annual_interest_rate:rate||"0",regular_payment:payment||"0",start_date:startDate,day_count_convention:convention})});setAccountName("");setPrincipal("");setPayment("");setRate("0");setNotice("Account created with audited opening ledger entry and initial rate");await refresh()}catch(e){setError(e instanceof Error?e.message:"Could not create account")}}
  async function editAccount(item:Account){const name=window.prompt("Account name",item.name)?.trim();if(!name)return;const regular=window.prompt("Regular payment",String(item.regular_payment));if(regular===null)return;const status=window.prompt("Status: active, paused, archived or settled",item.status)?.trim();if(!status)return;const reason=window.prompt("Reason for change","Account metadata updated")?.trim();if(!reason)return;try{await api(`/managed-accounts/${item.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,account_type:item.account_type,regular_payment:regular,status,reason})});setNotice("Account updated; ledger history was not changed");await refresh()}catch(e){setError(e instanceof Error?e.message:"Could not update account")}}
  async function archiveAccount(item:Account){if(!window.confirm(`Archive ${item.person} · ${item.name}? The ledger and audit history will be retained.`))return;try{await api(`/managed-accounts/${item.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:item.name,account_type:item.account_type,regular_payment:item.regular_payment,status:"archived",reason:"Account archived from management workspace"})});setNotice("Account archived; accounting history retained");await refresh()}catch(e){setError(e instanceof Error?e.message:"Could not archive account")}}
  return <div className="phase7-page"><header className="topbar"><div className="brand"><span className="brand-mark">BM</span><span>Bank of Mum</span></div><div className="workspace-title">Family accounting workspace <span>Phase 7 · people & accounts</span></div><div className="connection online"><i/>Management</div></header><main className="phase7-workspace">
    <section className="page-head"><div><p className="eyebrow">BANK OF MUM</p><h1>People & accounts</h1><p>Create and maintain family lending accounts without deleting accounting history.</p></div><a className="primary" href="/">Back to dashboard</a></section>
    {error&&<div className="notice error">{error}</div>}{notice&&<div className="notice success">{notice}</div>}
    <div className="phase7-cards"><article><small>People</small><strong>{people.length}</strong><span>Family members</span></article><article><small>Active accounts</small><strong>{activeAccounts.length}</strong><span>Excludes archived</span></article><article><small>Outstanding</small><strong>{money.format(activeAccounts.reduce((s,a)=>s+a.balance,0))}</strong><span>Calculated balance</span></article><article><small>Interest accrued</small><strong>{money.format(activeAccounts.reduce((s,a)=>s+a.accrued_interest,0))}</strong><span>Current accrued interest</span></article></div>
    <section className="phase7-grid equal"><div className="panel"><div className="panel-head"><div><p className="eyebrow">PEOPLE</p><h2>Add family member</h2></div></div><form className="phase7-form" onSubmit={addPerson}><label>Name<input value={personName} onChange={e=>setPersonName(e.target.value)} placeholder="Name"/></label><label>Notes<textarea value={personNotes} onChange={e=>setPersonNotes(e.target.value)} placeholder="Optional notes"/></label><button className="primary" type="submit">Create person</button></form><div className="table-scroll"><table className="phase7-table"><thead><tr><th>Name</th><th>Accounts</th><th>Notes</th><th/></tr></thead><tbody>{people.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.active_accounts} active</small></td><td>{item.accounts}</td><td>{item.notes||"—"}</td><td><button className="quiet-button" onClick={()=>void editPerson(item)}>Edit</button></td></tr>)}</tbody></table></div></div>
      <div className="panel"><div className="panel-head"><div><p className="eyebrow">ACCOUNTS</p><h2>Open lending account</h2></div></div><form className="phase7-form" onSubmit={addAccount}><label>Person<select value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">Select person</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Account name<input value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="Car, bike, loan…"/></label><div className="two"><label>Opening principal<input type="number" step="0.01" value={principal} onChange={e=>setPrincipal(e.target.value)}/></label><label>Regular payment<input type="number" step="0.01" value={payment} onChange={e=>setPayment(e.target.value)}/></label></div><div className="two"><label>Annual interest %<input type="number" step="0.000001" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Start date<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label></div><label>Day-count convention<select value={convention} onChange={e=>setConvention(e.target.value)}><option value="actual_365">Actual / 365</option><option value="actual_366">Actual / 366</option><option value="actual_actual">Actual / Actual</option><option value="30_360">30 / 360</option></select></label><button className="primary" type="submit" disabled={!people.length}>Create account</button><p className="form-hint">Opening principal is posted as an immutable ledger debit. The initial interest rate becomes the first append-only rate period.</p></form></div></section>
    <div style={{height:16}}/><section className="panel"><div className="panel-head"><div><p className="eyebrow">ACCOUNT REGISTER</p><h2>All accounts</h2></div><span>{accounts.length}</span></div><div className="table-scroll"><table className="phase7-table"><thead><tr><th>Person / account</th><th>Status</th><th>Start</th><th>Rate</th><th>Regular payment</th><th>Principal</th><th>Interest</th><th>Balance</th><th/></tr></thead><tbody>{accounts.map(item=><tr key={item.id}><td><strong>{item.person} · {item.name}</strong><small>{item.account_type}</small></td><td><span className={`status-pill ${item.status}`}>{item.status}</span></td><td>{item.start_date||"—"}</td><td>{item.annual_interest_rate}%</td><td className="money">{money.format(item.regular_payment)}</td><td className="money">{money.format(item.principal)}</td><td className="money">{money.format(item.accrued_interest)}</td><td className="money"><strong>{money.format(item.balance)}</strong></td><td><div className="phase7-actions"><button className="quiet-button" onClick={()=>void editAccount(item)}>Edit</button>{item.status!=="archived"&&<button className="danger-button" onClick={()=>void archiveAccount(item)}>Archive</button>}</div></td></tr>)}</tbody></table></div></section>
  </main></div>
}
